### ISSUE TITLE
Host service privately

### ISSUE THREAD

**Issue by mathetes87** [tensorflow/datasets#103]
Would it be possible to host a service to serve private datasets using tf-datasets?

**Comment by rsepassi** [comment]
Hi @mathetes87, great question. Here's what I'd recommend you do to host private datasets. We may want a document that details how to do this. Would you be interested in taking some of this, trying it out, and submitting a PR with documentation?

1. In your own private repository, add definitions of datasets as subclasses of `tfds.core.DatasetBuilder`, just like you would if you were contributing the datasets publicly.
2. Create a wrapper `tensorflow_datasets.py`. This will be the module that your internal users will use (i.e. instead of `import tensorflow_datasets as tfds`, they'll do `from my_private_codebase import tensorflow_datasets as tfds`). Inside this file:

  - add the imports for all your private dataset definitions; this will make your datasets register with `tfds`
  - add `from tensorflow_datasets import *`; this ensures that your wrapper exposes the same API as `tfds`
  - add `from tensorflow_datasets.core import constants; constants.DATA_DIR = "path/to/shared/private/directory"`; this makes the default data directory be some shared directory (for example, a GCS bucket).

3. Pre-generate all your datasets to the shared directory. That way, your internal users will never have to wait for data to prepare and they'll be able to read directly from the pre-processed files.

**Comment by mathetes87** [comment]
I would gladly do that! Next week I should have the time to test it.
Thanks!

**Comment by rsepassi** [comment]
Great, thanks!
