### ISSUE TITLE
Support nested structures in statistics.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/datasets#119]
This feature would be needed for at minimum the [CelebA dataset](https://github.com/tensorflow/datasets/blob/master/docs/datasets.md#celeb_a).

Nested structures could be stored on disk and documented in schema in a "flat" way, but have nesting in `as_dataset` and in the `FeatureDict` (for data gen). Whenever applicable, nesting / un-nesting should be consistent with [`tf.contrib.framework.nest.{flatten, pack_sequence_as}`](https://www.tensorflow.org/api_docs/python/tf/contrib/framework/nest).

**For example**, a feature nested at `a/b/c` could be stored and documented with the key 'a/b/c', but then returned in `as_dataset` nested within dicts (same for `FeatureDict` encode).

_Additional notes:_

* Statistics generation should first flatten the example, and then iterate on it.
* `FeatureConnector` supports both nested and `/` in the key (see [`features_test.py`](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/features/features_test.py#L61)).
* Features are automatically flattened during encoding and restored in [`decode_examples()`](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/features/features_test.py#L47).

With statistics computation, nested information will probably be lost during flattening (even if there may be a way to save the structure shape in another field). But because statistics are only there for information purposes, and because TensorFlow Datasets never depends on that information, it should not matter.

**Comment by kyscg** [comment]
I'd like to try my hand at fixing this issue, could you guide me through the process?

**Comment by Conchylicultor** [comment]
Thanks for looking at this.
Currently during data generation with statistics, if the feature dict contains nested features, statistics  computation are skipped here: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/dataset_info.py#L508

The idea would be still compute stats for those feature (probably by recursively iterating over `info.features.get_tensor_info()`).

Please also note that all this code will go away when we migrate statistics computations to https://github.com/tensorflow/data-validation

We didn't used tensorflow/data-validation originally because of lack of python3 support. Now that tensorflow/data-validation supports Python3, it may be time to migrate all the statistics computation to use tfdv.

If you feel motivated, you may want to look at replacing the `get_dataset_feature_statistics` function (https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/dataset_info.py#L436) by  tensorflow/data-validation instead.

**Comment by ParthS007** [comment]
@Conchylicultor I want to work on this. How should I proceed with this Issue? Thanks :)

**Comment by galeone** [comment]
The PR https://github.com/tensorflow/datasets/pull/445 is related to this issue

**Comment by tacho090** [comment]
Guess this issue can be closed because of PR #445 ?
