### ISSUE TITLE
site-packages/tensorflow_datasets/image/quickdraw_labels.txt : No such file or directory

### ISSUE THREAD

**Issue by ChanchalKumarMaji** [tensorflow/datasets#157]
**Short description**
using <code>pip install tensorflow-datasets</code> I downloaded the package. While running <code>document_datasets.py</code> raises the issue. I manually downloaded and transferred <code>quickdraw_labels.txt</code> to the correct place, then it worked.

![The issue is best described here](https://github.com/ChanchalKumarMaji/dataset/blob/master/Screenshot%20from%202019-03-04%2018-09-23.png)

**Environment information**
* Operating System: <Ubuntu-<code>18.04</code>>
* Python version: <<code>3.6</code>>

@rsepassi @Conchylicultor @cyfra @dynamicwebpaige  - Please tell me what to do so that I can start working on it.

**Comment by cyfra** [comment]
Thanks for reporting.

I think this is an issue on our side: we probably forgot to add this file to the pypi package (in setup.py).

In general: if you do the development, I'd suggest forking/fetching the code from github repo rather than pypi package (which is meant for end-users and doesn't have up-to-date code)
