### ISSUE TITLE
Kaggle downloader fails to download datasets

### ISSUE THREAD

**Issue by vijayphoenix** [tensorflow/datasets#1824]
**Short description**
When downloading datasets from Kaggle using `dl_manager.download_kaggle_data()` function, it throws the following errors.
```
NonMatchingChecksumError: Artifact kaggle://competition/digit-recognizer/sample_submission.csv, downloaded to /root/tensorflow_datasets/competiti_digit-recognize_sample_submissioIUxxdxSEdFK1_W-trEIDwYRuks7CiRMFvbzIvDrAFcA.csv.tmp.6ee33ceae48442718ab6db436f6115fe/sample_submission.csv, has wrong checksum.
```
and in some other datasets
```
NotFoundError: /root/tensorflow_datasets/data_fire_us-coun-covi-19-data_us-counMuhrcRpwHSpUuZrqFnl9FdmeJs90GcVIwO9g0KC7BiU.csv.tmp.9e67f4fae786466fa5303ff6cf7a030d/us-counties.csv; No such file or directory
```
**Environment information and Reproduction instructions**
Colab Link : [link](https://colab.research.google.com/drive/1kdqmjjp-Omg3GfKO4FthubegCnJUrNqf)

**Expected behavior**
It should download the dataset without any problem.

**Comment by blckwolf5851** [comment]
Some discussion about the first issue (NonMatchingChecksumError) was mentioned in this conversation: https://github.com/tensorflow/datasets/issues/1757

Below are just comments and question on the other issue, which might not be a solution to your issue:
Regarding the NotFoundError, I think there was something wrong with the line 115 in downloader.py, which lead to my other question about download_file method line 123 in kaggle.py (core.download.kaggle) which is why are we downloading individual file instead of downloading them all in once by using the command: kaggle competitions download -c [COMPETITION]

**Comment by vijayphoenix** [comment]
@blckwolf5851 I am not sure if I am able to follow you.

Also, the NonMatching checksum error in the above mentioned issue occured while adding a new dataset to tfds. 

So, I don't think both are related.
