### ISSUE TITLE
Colab uses old TFDS version

### ISSUE THREAD

**Issue by sgodfrey66** [tensorflow/datasets#2033]
**Short description**
To be honest, I'm not sure if this is a bug or how to consistently recreate the issue.  However, I found it challenging and others might as well.  In some cases, the tfds.load() method returns a DatasetV1Adapter object which seems to have a different set of methods than the expected Dataset.

Running this code snippet in Colab gave me errors (see Colab notebooks below) https://www.tensorflow.org/datasets?hl=en while the instructions at this link did not https://www.tensorflow.org/datasets/overview

It a tensor particular build is needed to easily use the datasets, it might be helpful to add to the documentation.

Thanks

**Environment information**
* Operating System: Colab, see below

**Reproduction instructions**

problematic:
https://colab.research.google.com/drive/11bYsDyFs0yqG3QRy51s1ijpeWoXkuz-B?usp=sharing

works:
https://colab.research.google.com/drive/1yYImYm7a2KEQBoEfHGtsa7O6tIJ2I7KD?usp=sharing

**Comment by Conchylicultor** [comment]
It seems that you are using an older version of TFDS.

With new versions of TFDS:
* `tfds.load` always returns a `tf.compat.v2.data.Dataset` object.
* `tfds.show_examples` accept `(ds, info)` (instead of `info, ds`). This change was done for consistency with `tfds.load`

It seems that you're passing the new argument order using the older version.

The default version of TFDS installed in Colab is old, but you can manually update it with `pip upgrade`.
I'll try to update the Colab to use the last TFDS version.

**Comment by sharanramjee** [comment]
I just ran `!pip install --upgrade tensorflow-datasets` and that fixed the issue.

**Comment by bhack** [comment]
The best approach is to open a ticket like https://github.com/googlecolab/colabtools/issues/1243

**Comment by vijayphoenix** [comment]
We should also update `tfds` version in Anaconda.
Anaconda has a very old [tfds-1.2.0](https://anaconda.org/anaconda/tensorflow-datasets)
