### ISSUE TITLE
Seeing 403 when trying to get "imdb_reviews" dataset

### ISSUE THREAD

**Issue by sunseaandpalms** [tensorflow/datasets#2059]
**Short description**
Seeing 403 when trying to get `"imdb_reviews"` dataset.

**Environment information**
* Operating System: `Win7`
* Python version: `3.7.7`
* `tensorflow-datasets`/`tfds-nightly` version:  `tfds-nightly==3.1.0.dev202005280105`
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version>

**Reproduction instructions**

```
tfds.load(name="imdb_reviews")
```

**Link to logs**
```
/lib/python3.7/site-packages/tensorflow_datasets/core/download/downloader.py in _sync_download(self, url, destination_path)
    233         iter(functools.partial(response.read, io.DEFAULT_BUFFER_SIZE), b''),
    234     )
--> 235 
    236 
    237 def _get_drive_url(url: str, session: requests.Session) -> str:

DownloadError: Failed to get url http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz. HTTP code: 403.
```

**Comment by vijayphoenix** [comment]
The `403 Forbidden Error` happens when the web page that you're trying to open is blocked for you.

Try to manually open the website in your browser. If it doesn't open then try to figure out why you are unable to open the website, for example, your internet service provider blocked it.

Using a VPN could be a possible fix.

**Comment by sunseaandpalms** [comment]
I see the link is just working right now. Mb the site was down.
