### ISSUE TITLE
More consistent `checksums.tsv`

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2420]
Currently, dataset checksums are saved as `checksums.tsv` but are not Tab-Separated-Values (but Space-Separated-Value).  This feel inconsistent.

We should update:
https://github.com/tensorflow/datasets/blob/3e90c815a61db5236063817cf699f2bd4d7eef58/tensorflow_datasets/core/download/checksums.py#L154
to save and load using tab instead of space.

* Current checksums should be updated to use tab.
* We should keep a backward compatibility mode with space while files gets updated.

Also I noticed
* `url_infos_from_path` and `_get_url_infos` seems redundant as they both do the same thing. This could be cleaned up

**Comment by NikhilBartwal** [comment]
@Conchylicultor I would like to take this issue.
As far as I understood we need to use `tab` instead of `space` in the following :

For retrieving:
https://github.com/tensorflow/datasets/blob/3e90c815a61db5236063817cf699f2bd4d7eef58/tensorflow_datasets/core/download/checksums.py#L154
 
For storing:
https://github.com/tensorflow/datasets/blob/3e90c815a61db5236063817cf699f2bd4d7eef58/tensorflow_datasets/core/download/checksums.py#L204

However, I don't quite get how to keep it backward compatible with space?

**Comment by Conchylicultor** [comment]
Thanks for looking into this. To keep it backward compatible, you can first try to load it as tab, then fallback to space if this fail

**Comment by NikhilBartwal** [comment]
@Conchylicultor I have fixed the `checksums `script and aded an `update_checksums `script for updating all checksum files (both .txt and .tsv).
Could you have a look at the PR? Thanks!

**Comment by vijayphoenix** [comment]
The issue seems to be fixed
