### ISSUE TITLE
Extraction bug for Github urls

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2423]
`dl_manager.download_and_extract` do not auto-detect the archive extension for github url (e.g. https://github.com/brendenlake/SCAN/archive/master.zip).

Currently, dataset creators are require to hardcode the extension format: https://github.com/tensorflow/datasets/blob/b9deaa07f567ad3211850a1e5c1ae993a1a03409/tensorflow_datasets/text/scan.py#L160

Fails (`data_dir` is downloaded but not extracted):
```py
data_dir = dl_manager.download_and_extract('https://github.com/brendenlake/SCAN/archive/master.zip')
```

Work:
```py
data_dir = dl_manager.download_and_extract(
        tfds.download.Resource(
            url='https://github.com/brendenlake/SCAN/archive/master.zip',
            extract_method=tfds.download.ExtractMethod.ZIP,
       ),
)
```

**Comment by vijayphoenix** [comment]
This bug occurs because we fail to pass the filename with extension.

We get the following response headers when we make a `get` request to the GitHub URLs. 
(In this example `https://github.com/mogutt/README/archive/master.zip`)
```
{
   "headers":{
      "Content-Disposition":"attachment; filename=README-master.zip",
      ...
   },
   "url":"https://codeload.github.com/mogutt/README/zip/master",
   ....
}
```

So, when we pass the above response to the `_get_filaname` function:

https://github.com/tensorflow/datasets/blob/bd47f95c35096232e7ace131ae725c4ebdc7b3d3/tensorflow_datasets/core/download/downloader.py#L47-L55

We get `master` as a return value.

**Comment by SuryashankarDas** [comment]
Right now if the the content-disposition is not enclosed within quotes, we cant get a match. How about we do something like, if the match is null after the first case, we check for a match without quotes? It worked out when I tried.

**Comment by Conchylicultor** [comment]
Thank you for fixing this bug.

As follow up, we should cleanup the `tfds.download.Resource` as in https://github.com/tensorflow/datasets/blob/b9deaa07f567ad3211850a1e5c1ae993a1a03409/tensorflow_datasets/text/scan.py#L160,
and check the download are still working.
