### ISSUE TITLE
Replacement for tfds.deprecated.text.SubwordTextEncoder

### ISSUE THREAD

**Issue by stefan-falk** [tensorflow/datasets#2879]
Unfortunately there is no statement addressing the deprecation of [`tfds.deprecated.text.SubwordTextEncoder`](https://www.tensorflow.org/datasets/api_docs/python/tfds/deprecated/text/SubwordTextEncoder).

Why was the `SubwordTextEncoder` deprecated? Will there be a replacement and what can/should we use instead?

**Comment by IIIBlueberry** [comment]
I think it was replaced by [tensorflow/text](https://github.com/tensorflow/text)

**Comment by stefan-falk** [comment]
@IIIBlueberry Hm, they do not seem to have a `SubwordTextEncoder` yet as far as I can see.

There's discussions about it: https://github.com/tensorflow/text/issues/417 but it seems nothing has materialized yet.

**Comment by Conchylicultor** [comment]
We've warned of this changed in our [release notes](https://github.com/tensorflow/datasets/releases) and were raising warning when user was using it.

The reason it is deprecated is because it was non maintained, had known bug and performance issues.

Tensorflow text as text.BertTokenizer or SentencepieceTokenizer which are subword tokenizer. There is also pretrained tokenizer that you can install from TF-Hub: like https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2

There

**Comment by stefan-falk** [comment]
Indeed, it was stated in [v3.2.0](https://github.com/tensorflow/datasets/releases/tag/v3.2.0).

`BertTokenizer` and `SentencepieceTokenizer` do not look like they can create a vocabulary for you so I guess this is something we have to do on our own now - except I am overlooking something.

@Conchylicultor thank you for clarification though. I guess my question is answered. :)

**Comment by Conchylicultor** [comment]
Yes, creating vocabulary isn't straightforward now. I believe TF-Text plan to make it easier. You should submit an issue on their repository to ask them directly.

**Comment by stefan-falk** [comment]
@Conchylicultor Will do, thank you! :)

**Comment by MarkDaoust** [comment]
> I believe TF-Text plan to make it easier. 

Yes. TFText has all the necessary classes to replace this. It's also implemented in tensorflow so you can export this preprocessing with the model.

I'm working on getting a tutorial published on how to do this.
