### ISSUE TITLE
wider_face download fails with a checksum error

### ISSUE THREAD

**Issue by maxcrous** [tensorflow/datasets#3018]
**Short description**
`tfds.load('wider_face')` fails with a checksum error, for multiple versions of tensorflow(-datasets), python, and on different operating systems.

**Environment information**
* Operating System: Ubuntu 20.0.4
* Python version: 3.8
* `tensorflow-datasets`/`tfds-nightly` version:  tensorflow-datasets 4.2.0
* `tensorflow`/`tf-nightly` version: tensorflow 2.4.1

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
The issue persists on ` tfds-nightly-4.2.0.dev202102040106` with `tf-nightly-2.5.0.dev20210204`

**Reproduction instructions**

```
import tensorflow_datasets as tfds
tfds.load('wider_face')
```

**Link to logs**
[Link to stack trace gist here.](https://gist.github.com/maxcrous/0f6ada3e9013efc1b4504e25ab5893c2)

**Expected behavior**
Dataset downloads without a checksum error.

**Additional context**
No additional context.

**Comment by maxcrous** [comment]
In the meantime, I'm using `tensorflow_datasets=4.1.0`, which does not throw an error for `wider_face`.

**Comment by Conchylicultor** [comment]
This is unrelated to the TFDS version. From the logs:
```
tensorflow_datasets.core.download.download_manager.NonMatchingChecksumError: 
Artifact https://drive.google.com/uc?export=download&id=0B6eKvaijfFUDbW4tdGpaYjgzZkU, downloaded to /home/maxcrous/tensorflow_datasets/downloads/ucexport_download_id_0B6eKvaijfFUDbW4tdGpaYjgzqpD1B9Dnv82IcKtgBzjedFSRfGEgujZCg3LdgCTEzOE.tmp.314b8e1f11a94d42b8739e3ff6752d20/uc, 
has wrong checksum. 
Expected: 
UrlInfo(size=1.72 GiB, checksum='3b0313e11ea292ec58894b47ac4c0503b230e12540330845d70a7798241f88d3', filename='WIDER_test.zip'). Got: 
UrlInfo(size=3.01 KiB, checksum='b15d6012372197a7237c0bd119d13388245e88845cd0cb310c4b0aa5917ddbe7', filename='uc').
To debug, see: https://www.tensorflow.org/datasets/overview#fixing_nonmatchingchecksumerror
```

The server on which the data is hosted has returned a 3Kib error message file instead of the expected zip file.

As explained in https://www.tensorflow.org/datasets/overview#fixing_nonmatchingchecksumerror, Google Drive sometimes rejects downloads when too many people access the same URL.

Unfortunately not much we can fix from our side. You can use https://www.tensorflow.org/datasets/overview#manual_download_if_download_fails or retry later.
