### ISSUE TITLE
Parallelise  `tfds.list_builder` when community dataset is used

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#3036]
Currently, when `tfds.list_builder()` is called, TFDS will sequentially try to list datasets in each of the registered data_dir which is very slow when there is many data_dir to look at:

https://github.com/tensorflow/datasets/blob/aa0547927fab3504a9980528c486bbe32a3b598c/tensorflow_datasets/core/community/register_path.py#L144

It would be nice if this sequential loop was parallelised, so all `list(path.iterdir())` are executed in parallel.

**Comment by NikhilBartwal** [comment]
Hey @Conchylicultor , I would like to take this up. Just so we are on the same page, we need to parallelize the nested sequential loop used in `_iter_builder_names`, so that all the different categories of datasets can be simultaneously loaded.

Also, I couldn't really understand the purpose of using `_maybe_iterdir` inside the nested loop:
https://github.com/tensorflow/datasets/blob/aa0547927fab3504a9980528c486bbe32a3b598c/tensorflow_datasets/core/community/register_path.py#L133
It would be great if you could provide me some direction. Thanks!

**Comment by Conchylicultor** [comment]
Only the first loop need to be parallelized: https://github.com/tensorflow/datasets/blob/aa0547927fab3504a9980528c486bbe32a3b598c/tensorflow_datasets/core/community/register_path.py#L150

So all namespaces are processed in parallel. `ns2data_dir` is a Dict like:
```
ns2data_dir = dict(
      kaggle=Path('/some/path'),
      mlds=Path('/some/other/path'),
      other=Path('/another/path'),
)
```

`_maybe_iterdir` is just like `path.iterdir()` but do not crash if the path don't exists (`Path('non_existing_path').iterdir()` raise error while `_maybe_iterdir(Path('non_existing_path'))` do not)

**Comment by NikhilBartwal** [comment]
@Conchylicultor I have made the PR for parallelizing `tfds.list_builders`. It would be great if you could have a look. Thanks!
