### ISSUE TITLE
cars196 link broken - needs updating

### ISSUE THREAD

**Issue by Tejas-Beedkar** [tensorflow/datasets#3219]
**Short description**
The path of the cars196 database has changed. In the file:

[](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image_classification/cars196.py)

Line 22: ` _URL = 'http://imagenet.stanford.edu/internal/car196/`

should be updated to 
Line22: `_URL = 'http://ai.stanford.edu/~jkrause/car196/'`

**Reproduction instructions**
Env - Google Colab Pro
```
      import tensorflow_datasets as tfds
      ds = tfds.load("cars196", split='train', shuffle_files=True)
```

Log:
`      DownloadError: Failed to get url https://image-net.org/internal/car196/cars_test.tgz. HTTP code: 404.`

**Comment by NikhilBartwal** [comment]
Hey @Tejas-Beedkar, this issue was recently detected and PR #3197 has been made to address this. 
You can use the dataset in the updated `tfds-nightly` once the PR gets merged.

@Conchylicultor There has been multiple issues for the `cars196` dataset. Would be great if you could have a look at the PR. Thanks!

**Comment by Tejas-Beedkar** [comment]
Thanks Nikhil. I gave a approval for the review in PR #3197 assuming the system will filter me out if I am not supposed to.
I verified that the currently nightly build is not updated:
```
!pip install -q tfds-nightly tensorflow matplotlib
import tensorflow_datasets as tfds
ds = tfds.load("cars196", split='train', shuffle_files=True)
```
I will try again tomorrow. Thanks for your help!
