### ISSUE TITLE
Importing tensorflow_datasets changes root logger's format

### ISSUE THREAD

**Issue by carlthome** [tensorflow/datasets#354]
`logging`'s root logger format is changed after importing tensorflow_datasets. It's unexpected behaviour and shouldn't happen IMO.

**Environment information**
* Operating System: Ubuntu 18.10
* Python version: Python 3.6
* `tensorflow-datasets`/`tfds-nightly` version: 1.0.1
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 1.12.0

**Reproduction instructions**

```python
In [1]: import tensorflow as tf

In [2]: import logging

In [3]: logging.warning("foo")
WARNING:root:foo

In [4]: import tensorflow_datasets

In [5]: logging.warning("foo")
WARNING: Logging before flag parsing goes to stderr.
W0326 16:19:52.991167 140346537146176 <ipython-input-6-922a11d7ac8e>:1] foo
```

**Comment by rsepassi** [comment]
Hmm..that is unfortunate, but it seems that it's `absl` that's modifying it:

```
import logging
logging.warn("foo")
from absl import logging as absl_log
logging.warn("foo")
```

**Comment by lgeiger** [comment]
Indeed it is a issue with `absl`: https://github.com/abseil/abseil-py/issues/99

This is also the case for `tensorflow` itself: https://github.com/tensorflow/tensorflow/issues/23559
It seams there are efforts in TF to remove the custom logging entirely because it breaks users who use Pythons  `logging` module.

@rsepassi Is there any reason why `absl.logging` is used instead of the default `logging` module?

**Comment by Conchylicultor** [comment]
According to https://github.com/abseil/abseil-py/issues/99#issuecomment-525390675, absl.logging no longer registers itself at import time.
Closing this as it should be fixed.
