### ISSUE TITLE
[data request] Mathematics Dataset

### ISSUE THREAD

**Issue by SoumyadeepJana** [tensorflow/datasets#489]
* Name of dataset: Mathematics Dataset
* URL of dataset: https://github.com/deepmind/mathematics_dataset
* License of dataset: Apache License 2.0
* Short description of dataset and use case(s): A large-scale extendable dataset which generates question and answer pairs from a range of question types at roughly school-level difficulty. It is designed to test the mathematical learning and algebraic reasoning skills of learning models.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by SoumyadeepJana** [comment]
@Conchylicultor @rsepassi @cyfra I have started working on this dataset.Please assign me.

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as Math Dataset is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/math_dataset.py and https://www.tensorflow.org/datasets/catalog/math_dataset for more info.
Thank you for your contribution
