### ISSUE TITLE
_normalize_drive_url(url: str) failed to bypass Google Drive Warning

### ISSUE THREAD

**Issue by OmkarBorhade98** [tensorflow/datasets#4924]
**Short description**
I was trying to load a_celeb dataset. While doing so, I encountered that it wasn't able to download image files from drive. on debugging tensorflow_dataset code, I found that the function [`_normalize_drive_url(url: str)`](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/download/downloader.py#LL319C3-L319C3), which is meant to bypass "Google Drive can't scan this file for viruses" warning when downloading large files, is generating necessary URL. The function just adds `&confirm=t` to the link, which is not enough to by pass the warning.

**Environment information**
* Operating System: Windows 10
* Python version: 3.10.11
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets 4.9.2
* `tensorflow`/`tf-nightly` version: tensorflow 2.12.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
Yes

**Reproduction instructions**

```python
import tensorflow as tf
import tensorflow_datasets as tfds
ds = tfds.load('celeb_a')
```

**Link to logs**
[Logs](https://gist.github.com/OmkarBorhade98/b65f4aae9c5a1d19957831bac228c103)

**Comment by fineguy** [comment]
Hi Omkar

Thank you so much for bringing this issue to our attention!

The error messages says at the end `... HTTP code: 429.`. It's an error from Google Drive caused by too many users having viewed or downloaded this file recently. You should wait for 24 hours before the file could be downloaded again. 

Could you please confirm that you're able to download it now?

**Comment by OmkarBorhade98** [comment]
Oh yes! I'm able to download it now. Thanks for the help :)
