### ISSUE TITLE
[data request] speech command

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/datasets#581]
* Name of dataset:  speech command
* URL of dataset: 
http://download.tensorflow.org/data/speech_commands_v0.01.tar.gz
http://download.tensorflow.org/data/speech_commands_v0.02.tar.gz

* License of dataset:  not known
* Short description of dataset and use case(s): 
https://arxiv.org/abs/1804.03209

**Comment by haideraltahan** [comment]
I can have it done, assign me to it

**Comment by haideraltahan** [comment]
Pull request created #992

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as Speech Command is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/audio/speech_commands.py and https://www.tensorflow.org/datasets/catalog/speech_commands for more info
Thank you for your contribution
