### ISSUE TITLE
Add multiprocessing support for tfrecord round-robin writer?

### ISSUE THREAD

**Issue by npuichigo** [tensorflow/datasets#676]
I found that sometimes writing shared tfrecords is slow. Will tensorflow_datasets plans to enhance the round-robin writer function to support multiprocessing?

**Comment by pierrot0** [comment]
Our recommended solution for large datasets is to use beam. You can run beam on a single machine and that's equivalent to multiprocessing, or on multiple machines, and that's distributed.

Current tfrecord round-robin writer is going away, to be replaced eventually by tfrecords_writer.
tfrecords_writer sorts records according to a key, and write in order of that sorting, across shards. This is done so slicing API can be deterministic, irrespectively of number of shards. While we could technically use multiprocessing here, I don't think we will, since beam should probably be used for larger datasets.

Beam support for ordered writing of tfrecods: issue  #677.

**Comment by npuichigo** [comment]
@pierrot0 Thanks for your reply.

**Comment by amulya-radai** [comment]
Is there a way to shard the tfrecords in round robin fashion without using apache beam?

**Comment by pierrot0** [comment]
Note that https://github.com/tensorflow/datasets/issues/856 sounds very similar and is being worked on by Recep.
