### ISSUE TITLE
[data request] CIFAR-10.1

### ISSUE THREAD

**Issue by mjwillson** [tensorflow/datasets#738]
* Name of dataset: CIFAR-10.1
* URL of dataset: https://github.com/modestyachts/CIFAR-10.1
* License of dataset: their code: MIT, underlying TinyImages data: unspecified (?)
* Short description of dataset and use case(s):
**A new test set for CIFAR-10**. CIFAR-10.1 contains roughly 2,000 new test images that were sampled after multiple years of research on the original CIFAR-10 dataset. The data collection for CIFAR-10.1 was designed to minimize distribution shift relative to the original dataset. We describe the creation of CIFAR-10.1 in the paper "Do CIFAR-10 Classifiers Generalize to CIFAR-10?". The images in CIFAR-10.1 are a subset of the TinyImages dataset.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as CIFAR - 10.1 is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image_classification/cifar10_1.py and https://www.tensorflow.org/datasets/catalog/cifar10_1 for more info.
Thank you for your contribution
