### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by us** [tensorflow/datasets#829]
**Is your feature request related to a problem? Please describe.**
When installing tfds for testing, using api, `python setup.py install` given error because of dependencies.
**Describe the solution you'd like**
`requirements.txt` solve the problem.

**Comment by Conchylicultor** [comment]
Can you detail the error that you get when running `python setup.py install` ?
Currently the dependencies are hardcoded in the `setup.py` file, because not all dependencies are always required (ex: some are only required for tests, or for specific dataset). How would this works with `requirements.txt` ?

**Comment by us** [comment]
For the basic one example, `tensorflow` is not installing with `setup.py`. 
At least we can add basic things of this repo, just to use the api without installing the package

**Comment by Conchylicultor** [comment]
Closing this as `setup.py` should be the only source of truth. For TensorFlow, we explicitly do not link the version to tfds to let the users install the version of their choice (nightly VS official). Maybe we should but this would be another issue.

Having an additional file would duplicate the dependencies and would be harder to maintain.
