### ISSUE TITLE
Script to generate list of datasets with their versions

### ISSUE THREAD

**Issue by pierrot0** [tensorflow/datasets#884]
Problem: Right now, there is no easy way to tell what are the available versions of each dataset, beside looking at the source code.

We want to ask people to pin the major component of the version they are using.

Proposed solution:
Have a script / function to generate the list of datasets with their available versions (and which is the canonical).

 We already have a function to generate the list of datasets. Maybe we can just update it.
The description of what each function is about is not available programmatically, so I would just have the versions, it's sufficient for now.

**Comment by Conchylicultor** [comment]
Instead of creating a new list, I think this information should be included in the current dataset documentation instead.
This could also be added programatically. Something like: `builder.info.print_available_versions()`

Additionally, maybe release note should be part of `tfds.core.Version('1.1.0', release_note='Add new text field')`, instead of being a comment. This would allow the above functions to provide more information. And we could surface those release note when an error is raised about versioning.

**Comment by pierrot0** [comment]
Agree on the release notes eventually being part of the version. But next
iteration. For now it would already be nice to have a list with versions.
