### ISSUE TITLE
Celeb_a wrong checksum

### ISSUE THREAD

**Issue by EmanueleGhelfi** [tensorflow/datasets#943]
**Short description**
NonMatchingChecksumError when downloading celeb_a dataset

**Environment information**
* Operating System: Arch Linux
* Python version: 3.7
* `tensorflow-datasets` version: 1.2.0
* `tensorflow` version: 2.0.0rc0

**Reproduction instructions**

```
import tensorflow datasets as tfds
tfds.load('celeb_a')
```

**Link to logs**
https://gist.github.com/EmanueleGhelfi/ea7b5684036262ff402c85e11db7dd3b

**Comment by EmanueleGhelfi** [comment]
I've tried again and I'm not encountering the issue anymore. Closing the issue.

**Comment by jzazo** [comment]
The following code gives me that same error:

```
import tensorflow.compat.v2 as tf
import tensorflow_datasets as tfds
tfds.disable_progress_bar()
tf.enable_v2_behavior()
celeb_a = tfds.load(name="celeb_a")
```

Any idea how to fix this? Thanks!

**Comment by VMBoehm** [comment]
I think it's due to an incomplete download. The dataset is pretty big and sometimes the download fails. I ran into the same error when I tried to download the dataset directly from the gdrive link, so it might not be a tfds issue at all. I think hosting the data on gdrive is just an unfortunate choice, since it's not meant for the purpose of sharing such big datasets. Sometimes it works after several attempts 9as reported above), or maybe you can find another channel for getting the data.

**Comment by jzazo** [comment]
I downloaded the `img_align_celeba.zip` directly from the Google Drive, and I was trying to set it up with `tfds.load(name="celeb_a", data_dir=my_unzipped_folder)`, but it tells me

`ConnectionError: HTTPConnectionPool(host='storage.googleapis.com', port=80): Max retries exceeded with url: /tfds-data/dataset_info/celeb_a/2.0.0/dataset_info.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff7b7ec9190>: Failed to establish a new connection: [Errno 24] Too many open files'))`

If I use `tfds.builder("celeb_a")` I get `ResourceExhaustedError: /home/javier/tensorflow_datasets/celeb_a; Too many open files`. 

Could you please tell me how to load and process the dataset as easily as possible after downloading it manually? Thank you!

**Comment by charleswilmot** [comment]
The problem still occurs with `tensorflow 2.3.0` and `tensorflow-dataset 1.2.0`

**Comment by Conchylicultor** [comment]
For info `tensorflow-dataset 1.2.0` is a very old version. I would strongly encourage you to use more recent version.

With recent TFDS, you can manually download the data yourself. See: https://www.tensorflow.org/datasets/overview#manual_download_if_download_fails
